# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'RealEstate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RealEstate
    pod 'Alamofire', '~> 4.4'
    pod 'AlamofireImage', '~> 3.1'
    pod 'RealmSwift'

end
